/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as ManageRouteImport } from './routes/manage'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as GroceryRouteImport } from './routes/grocery'
import { Route as IndexRouteImport } from './routes/index'

const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRoute = ManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const GroceryRoute = GroceryRouteImport.update({
  id: '/grocery',
  path: '/grocery',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/grocery': typeof GroceryRoute
  '/inventory': typeof InventoryRoute
  '/manage': typeof ManageRoute
  '/recipes': typeof RecipesRoute
  '/usage': typeof UsageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/grocery': typeof GroceryRoute
  '/inventory': typeof InventoryRoute
  '/manage': typeof ManageRoute
  '/recipes': typeof RecipesRoute
  '/usage': typeof UsageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/grocery': typeof GroceryRoute
  '/inventory': typeof InventoryRoute
  '/manage': typeof ManageRoute
  '/recipes': typeof RecipesRoute
  '/usage': typeof UsageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/grocery' | '/inventory' | '/manage' | '/recipes' | '/usage'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/grocery' | '/inventory' | '/manage' | '/recipes' | '/usage'
  id:
    | '__root__'
    | '/'
    | '/grocery'
    | '/inventory'
    | '/manage'
    | '/recipes'
    | '/usage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GroceryRoute: typeof GroceryRoute
  InventoryRoute: typeof InventoryRoute
  ManageRoute: typeof ManageRoute
  RecipesRoute: typeof RecipesRoute
  UsageRoute: typeof UsageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grocery': {
      id: '/grocery'
      path: '/grocery'
      fullPath: '/grocery'
      preLoaderRoute: typeof GroceryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GroceryRoute: GroceryRoute,
  InventoryRoute: InventoryRoute,
  ManageRoute: ManageRoute,
  RecipesRoute: RecipesRoute,
  UsageRoute: UsageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
